apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qntjid91o-java-springboot
  janus-idp.io/tekton: qntjid91o-java-springboot
  backstage.io/kubernetes-id: qntjid91o-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qntjid91o-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
